"""Add Review Model

Revision ID: 4c09f5c7e287
Revises: 9a975e8dbf1d
Create Date: 2024-05-13 10:55:04.265804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c09f5c7e287'
down_revision = '9a975e8dbf1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], name=op.f('fk_reviews_game_games')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
